# Let's use full HD as a base resolution for our game!
VIEWPORT_WIDTH = 1920
VIEWPORT_HEIGHT = 1080

COLLISION_TRIGGER_PLAYER = 1
COLLISION_TRIGGER_ENEMY = 2
COLLISION_TRIGGER_MG_BULLET = 3
COLLISION_TRIGGER_GRENADE_LAUNCHER_BULLET = 4
COLLISION_TRIGGER_FORCE_GUN_BULLET = 5

PLAYER_SPEED = 150
FORCE_GUN_BULLET_SPEED = 300
MACHINE_GUN_BULLET_SPEED = 1200
GRENADE_LAUNCHER_BULLET_SPEED = 200